"""The ontology starters' terms, with the IRIs SPARQL uses for them.

Generated by database/scripts/gen-starter-terms.mjs from
database/crates/lbb-ontology/starters/<id>.json. Do not edit: run
database/scripts/gen-clients.sh.

Usage: ``from lbb.starters import crm``, then ``crm.classes.Organization.iri``.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class StarterClass:
    """A class of a starter. ``super_types`` are its direct parents, by name."""

    name: str
    iri: str
    super_types: tuple[str, ...]


@dataclass(frozen=True)
class StarterProperty:
    """A property of a starter. Properties are global: one value type each."""

    name: str
    iri: str
    value_type: str


@dataclass(frozen=True)
class StarterRelation:
    """A relation of a starter. ``inverse`` names the reverse direction."""

    name: str
    iri: str
    domain: tuple[str, ...]
    range: tuple[str, ...]
    cardinality: str
    inverse: str | None
    inverse_iri: str | None


@dataclass(frozen=True)
class StarterQuestion:
    """A question the starter's ontology answers, with its SPARQL when one exists."""

    id: str
    text: str
    sparql: str | None


class _CrmClasses:
    Party = StarterClass(name="Party", iri="https://littlebigbrain.com/class/party", super_types=())
    Organization = StarterClass(name="Organization", iri="https://littlebigbrain.com/class/organization", super_types=("Party",))
    Person = StarterClass(name="Person", iri="https://littlebigbrain.com/class/person", super_types=("Party",))
    User = StarterClass(name="User", iri="https://littlebigbrain.com/class/user", super_types=("Person",))
    Team = StarterClass(name="Team", iri="https://littlebigbrain.com/class/team", super_types=())
    Task = StarterClass(name="Task", iri="https://littlebigbrain.com/class/task", super_types=())
    Pipeline = StarterClass(name="Pipeline", iri="https://littlebigbrain.com/class/pipeline", super_types=())
    Stage = StarterClass(name="Stage", iri="https://littlebigbrain.com/class/stage", super_types=())
    Lead = StarterClass(name="Lead", iri="https://littlebigbrain.com/class/lead", super_types=("Party",))
    Deal = StarterClass(name="Deal", iri="https://littlebigbrain.com/class/deal", super_types=())
    Ticket = StarterClass(name="Ticket", iri="https://littlebigbrain.com/class/ticket", super_types=())
    Activity = StarterClass(name="Activity", iri="https://littlebigbrain.com/class/activity", super_types=())
    Call = StarterClass(name="Call", iri="https://littlebigbrain.com/class/call", super_types=("Activity",))
    Email = StarterClass(name="Email", iri="https://littlebigbrain.com/class/email", super_types=("Activity",))
    Meeting = StarterClass(name="Meeting", iri="https://littlebigbrain.com/class/meeting", super_types=("Activity",))
    Note = StarterClass(name="Note", iri="https://littlebigbrain.com/class/note", super_types=("Activity",))
    Product = StarterClass(name="Product", iri="https://littlebigbrain.com/class/product", super_types=())
    LineItem = StarterClass(name="LineItem", iri="https://littlebigbrain.com/class/lineitem", super_types=())
    Quote = StarterClass(name="Quote", iri="https://littlebigbrain.com/class/quote", super_types=())
    Campaign = StarterClass(name="Campaign", iri="https://littlebigbrain.com/class/campaign", super_types=())


class _CrmProperties:
    source_system = StarterProperty(name="source_system", iri="https://littlebigbrain.com/p/source_system", value_type="keyword")
    source_id = StarterProperty(name="source_id", iri="https://littlebigbrain.com/p/source_id", value_type="keyword")
    source_url = StarterProperty(name="source_url", iri="https://littlebigbrain.com/p/source_url", value_type="keyword")
    source_updated_at = StarterProperty(name="source_updated_at", iri="https://littlebigbrain.com/p/source_updated_at", value_type="date_time")
    source_key = StarterProperty(name="source_key", iri="https://littlebigbrain.com/p/source_key", value_type="keyword")
    text = StarterProperty(name="text", iri="https://littlebigbrain.com/p/text", value_type="text")
    acl = StarterProperty(name="acl", iri="https://littlebigbrain.com/p/acl", value_type="keyword_set")
    created_at = StarterProperty(name="created_at", iri="https://littlebigbrain.com/p/created_at", value_type="date_time")
    modified_at = StarterProperty(name="modified_at", iri="https://littlebigbrain.com/p/modified_at", value_type="date_time")
    description = StarterProperty(name="description", iri="https://littlebigbrain.com/p/description", value_type="text")
    phone = StarterProperty(name="phone", iri="https://littlebigbrain.com/p/phone", value_type="keyword")
    website = StarterProperty(name="website", iri="https://littlebigbrain.com/p/website", value_type="keyword")
    street_address = StarterProperty(name="street_address", iri="https://littlebigbrain.com/p/street_address", value_type="keyword")
    city = StarterProperty(name="city", iri="https://littlebigbrain.com/p/city", value_type="keyword")
    region = StarterProperty(name="region", iri="https://littlebigbrain.com/p/region", value_type="keyword")
    postal_code = StarterProperty(name="postal_code", iri="https://littlebigbrain.com/p/postal_code", value_type="keyword")
    country = StarterProperty(name="country", iri="https://littlebigbrain.com/p/country", value_type="keyword")
    linkedin_url = StarterProperty(name="linkedin_url", iri="https://littlebigbrain.com/p/linkedin_url", value_type="keyword")
    lifecycle_stage = StarterProperty(name="lifecycle_stage", iri="https://littlebigbrain.com/p/lifecycle_stage", value_type="keyword")
    domain = StarterProperty(name="domain", iri="https://littlebigbrain.com/p/domain", value_type="keyword")
    industry = StarterProperty(name="industry", iri="https://littlebigbrain.com/p/industry", value_type="keyword")
    annual_revenue = StarterProperty(name="annual_revenue", iri="https://littlebigbrain.com/p/annual_revenue", value_type="f64")
    employee_count = StarterProperty(name="employee_count", iri="https://littlebigbrain.com/p/employee_count", value_type="i64")
    company_type = StarterProperty(name="company_type", iri="https://littlebigbrain.com/p/company_type", value_type="keyword")
    first_name = StarterProperty(name="first_name", iri="https://littlebigbrain.com/p/first_name", value_type="keyword")
    last_name = StarterProperty(name="last_name", iri="https://littlebigbrain.com/p/last_name", value_type="keyword")
    email = StarterProperty(name="email", iri="https://littlebigbrain.com/p/email", value_type="keyword")
    job_title = StarterProperty(name="job_title", iri="https://littlebigbrain.com/p/job_title", value_type="keyword")
    mobile_phone = StarterProperty(name="mobile_phone", iri="https://littlebigbrain.com/p/mobile_phone", value_type="keyword")
    company_name = StarterProperty(name="company_name", iri="https://littlebigbrain.com/p/company_name", value_type="keyword")
    lead_status = StarterProperty(name="lead_status", iri="https://littlebigbrain.com/p/lead_status", value_type="keyword")
    lead_source = StarterProperty(name="lead_source", iri="https://littlebigbrain.com/p/lead_source", value_type="keyword")
    is_active = StarterProperty(name="is_active", iri="https://littlebigbrain.com/p/is_active", value_type="bool")
    amount = StarterProperty(name="amount", iri="https://littlebigbrain.com/p/amount", value_type="f64")
    currency = StarterProperty(name="currency", iri="https://littlebigbrain.com/p/currency", value_type="keyword")
    unit_price = StarterProperty(name="unit_price", iri="https://littlebigbrain.com/p/unit_price", value_type="f64")
    quantity = StarterProperty(name="quantity", iri="https://littlebigbrain.com/p/quantity", value_type="f64")
    discount = StarterProperty(name="discount", iri="https://littlebigbrain.com/p/discount", value_type="f64")
    budget = StarterProperty(name="budget", iri="https://littlebigbrain.com/p/budget", value_type="f64")
    close_date = StarterProperty(name="close_date", iri="https://littlebigbrain.com/p/close_date", value_type="date_time")
    probability = StarterProperty(name="probability", iri="https://littlebigbrain.com/p/probability", value_type="f64")
    deal_type = StarterProperty(name="deal_type", iri="https://littlebigbrain.com/p/deal_type", value_type="keyword")
    forecast_category = StarterProperty(name="forecast_category", iri="https://littlebigbrain.com/p/forecast_category", value_type="keyword")
    is_closed = StarterProperty(name="is_closed", iri="https://littlebigbrain.com/p/is_closed", value_type="bool")
    is_won = StarterProperty(name="is_won", iri="https://littlebigbrain.com/p/is_won", value_type="bool")
    lost_reason = StarterProperty(name="lost_reason", iri="https://littlebigbrain.com/p/lost_reason", value_type="text")
    next_step = StarterProperty(name="next_step", iri="https://littlebigbrain.com/p/next_step", value_type="text")
    object_type = StarterProperty(name="object_type", iri="https://littlebigbrain.com/p/object_type", value_type="keyword")
    display_order = StarterProperty(name="display_order", iri="https://littlebigbrain.com/p/display_order", value_type="i64")
    stage_category = StarterProperty(name="stage_category", iri="https://littlebigbrain.com/p/stage_category", value_type="keyword")
    priority = StarterProperty(name="priority", iri="https://littlebigbrain.com/p/priority", value_type="keyword")
    category = StarterProperty(name="category", iri="https://littlebigbrain.com/p/category", value_type="keyword")
    channel = StarterProperty(name="channel", iri="https://littlebigbrain.com/p/channel", value_type="keyword")
    closed_at = StarterProperty(name="closed_at", iri="https://littlebigbrain.com/p/closed_at", value_type="date_time")
    occurred_at = StarterProperty(name="occurred_at", iri="https://littlebigbrain.com/p/occurred_at", value_type="date_time")
    direction = StarterProperty(name="direction", iri="https://littlebigbrain.com/p/direction", value_type="keyword")
    duration_seconds = StarterProperty(name="duration_seconds", iri="https://littlebigbrain.com/p/duration_seconds", value_type="i64")
    status = StarterProperty(name="status", iri="https://littlebigbrain.com/p/status", value_type="keyword")
    outcome = StarterProperty(name="outcome", iri="https://littlebigbrain.com/p/outcome", value_type="keyword")
    from_address = StarterProperty(name="from_address", iri="https://littlebigbrain.com/p/from_address", value_type="keyword")
    to_addresses = StarterProperty(name="to_addresses", iri="https://littlebigbrain.com/p/to_addresses", value_type="keyword_set")
    start_at = StarterProperty(name="start_at", iri="https://littlebigbrain.com/p/start_at", value_type="date_time")
    end_at = StarterProperty(name="end_at", iri="https://littlebigbrain.com/p/end_at", value_type="date_time")
    location = StarterProperty(name="location", iri="https://littlebigbrain.com/p/location", value_type="keyword")
    due_at = StarterProperty(name="due_at", iri="https://littlebigbrain.com/p/due_at", value_type="date_time")
    completed_at = StarterProperty(name="completed_at", iri="https://littlebigbrain.com/p/completed_at", value_type="date_time")
    sku = StarterProperty(name="sku", iri="https://littlebigbrain.com/p/sku", value_type="keyword")
    expires_at = StarterProperty(name="expires_at", iri="https://littlebigbrain.com/p/expires_at", value_type="date_time")
    campaign_type = StarterProperty(name="campaign_type", iri="https://littlebigbrain.com/p/campaign_type", value_type="keyword")


class _CrmRelations:
    WORKS_AT = StarterRelation(name="WORKS_AT", iri="https://littlebigbrain.com/r/works_at", domain=("Person",), range=("Organization",), cardinality="many_to_many", inverse="EMPLOYS", inverse_iri="https://littlebigbrain.com/r/employs")
    REPORTS_TO = StarterRelation(name="REPORTS_TO", iri="https://littlebigbrain.com/r/reports_to", domain=("Person",), range=("Person",), cardinality="many_to_one", inverse="MANAGES", inverse_iri="https://littlebigbrain.com/r/manages")
    SUBSIDIARY_OF = StarterRelation(name="SUBSIDIARY_OF", iri="https://littlebigbrain.com/r/subsidiary_of", domain=("Organization",), range=("Organization",), cardinality="many_to_one", inverse="HAS_SUBSIDIARY", inverse_iri="https://littlebigbrain.com/r/has_subsidiary")
    OWNED_BY = StarterRelation(name="OWNED_BY", iri="https://littlebigbrain.com/r/owned_by", domain=("Party", "Deal", "Ticket", "Activity"), range=("User",), cardinality="many_to_one", inverse="OWNS", inverse_iri="https://littlebigbrain.com/r/owns")
    ASSIGNED_TO = StarterRelation(name="ASSIGNED_TO", iri="https://littlebigbrain.com/r/assigned_to", domain=("Task",), range=("User",), cardinality="many_to_one", inverse="ASSIGNEE_OF", inverse_iri="https://littlebigbrain.com/r/assignee_of")
    MEMBER_OF = StarterRelation(name="MEMBER_OF", iri="https://littlebigbrain.com/r/member_of", domain=("User",), range=("Team",), cardinality="many_to_many", inverse="HAS_MEMBER", inverse_iri="https://littlebigbrain.com/r/has_member")
    FOR_ORGANIZATION = StarterRelation(name="FOR_ORGANIZATION", iri="https://littlebigbrain.com/r/for_organization", domain=("Deal", "Ticket", "Quote"), range=("Organization",), cardinality="many_to_many", inverse="ORGANIZATION_OF", inverse_iri="https://littlebigbrain.com/r/organization_of")
    INVOLVES = StarterRelation(name="INVOLVES", iri="https://littlebigbrain.com/r/involves", domain=("Deal", "Ticket"), range=("Person",), cardinality="many_to_many", inverse="INVOLVED_IN", inverse_iri="https://littlebigbrain.com/r/involved_in")
    ABOUT = StarterRelation(name="ABOUT", iri="https://littlebigbrain.com/r/about", domain=("Activity", "Task"), range=("Party", "Deal", "Ticket"), cardinality="many_to_many", inverse="HAS_ACTIVITY", inverse_iri="https://littlebigbrain.com/r/has_activity")
    IN_STAGE = StarterRelation(name="IN_STAGE", iri="https://littlebigbrain.com/r/in_stage", domain=("Deal", "Ticket"), range=("Stage",), cardinality="many_to_one", inverse="STAGE_HOLDS", inverse_iri="https://littlebigbrain.com/r/stage_holds")
    IN_PIPELINE = StarterRelation(name="IN_PIPELINE", iri="https://littlebigbrain.com/r/in_pipeline", domain=("Stage",), range=("Pipeline",), cardinality="many_to_one", inverse="PIPELINE_HOLDS", inverse_iri="https://littlebigbrain.com/r/pipeline_holds")
    HAS_LINE_ITEM = StarterRelation(name="HAS_LINE_ITEM", iri="https://littlebigbrain.com/r/has_line_item", domain=("Deal", "Quote"), range=("LineItem",), cardinality="many_to_many", inverse="LINE_ITEM_OF", inverse_iri="https://littlebigbrain.com/r/line_item_of")
    FOR_PRODUCT = StarterRelation(name="FOR_PRODUCT", iri="https://littlebigbrain.com/r/for_product", domain=("LineItem",), range=("Product",), cardinality="many_to_one", inverse="SOLD_AS", inverse_iri="https://littlebigbrain.com/r/sold_as")
    QUOTE_FOR = StarterRelation(name="QUOTE_FOR", iri="https://littlebigbrain.com/r/quote_for", domain=("Quote",), range=("Deal",), cardinality="many_to_one", inverse="HAS_QUOTE", inverse_iri="https://littlebigbrain.com/r/has_quote")
    IN_CAMPAIGN = StarterRelation(name="IN_CAMPAIGN", iri="https://littlebigbrain.com/r/in_campaign", domain=("Person", "Lead"), range=("Campaign",), cardinality="many_to_many", inverse="HAS_CAMPAIGN_MEMBER", inverse_iri="https://littlebigbrain.com/r/has_campaign_member")
    CONVERTED_TO = StarterRelation(name="CONVERTED_TO", iri="https://littlebigbrain.com/r/converted_to", domain=("Lead",), range=("Person", "Organization", "Deal"), cardinality="many_to_many", inverse="CONVERTED_FROM", inverse_iri="https://littlebigbrain.com/r/converted_from")


class _Crm:
    """The CRM starter 1.0.0."""

    id = "crm"
    version = "1.0.0"
    label = "CRM"
    classes = _CrmClasses
    properties = _CrmProperties
    relations = _CrmRelations
    questions: tuple[StarterQuestion, ...] = (
        StarterQuestion(id="crm-01", text="Which organizations does a person work at, and with what job title?", sparql="PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX p: <https://littlebigbrain.com/p/>\nPREFIX r: <https://littlebigbrain.com/r/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n\nSELECT ?person ?organization ?job_title WHERE {\n  # Input: a person's name. UNDEF answers for every person.\n  VALUES ?person { UNDEF }\n  ?x a/rdfs:subClassOf* c:person ;\n     rdfs:label ?person ;\n     r:works_at ?o .\n  ?o a/rdfs:subClassOf* c:organization ;\n     rdfs:label ?organization .\n  OPTIONAL { ?x p:job_title ?job_title }\n}\nORDER BY ?person ?organization\n"),
        StarterQuestion(id="crm-02", text="Which deals are open for an organization, with their amount and stage?", sparql="PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX p: <https://littlebigbrain.com/p/>\nPREFIX r: <https://littlebigbrain.com/r/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n\nSELECT ?organization ?deal ?amount ?currency ?stage WHERE {\n  # Input: an organization's name. UNDEF answers for every organization.\n  VALUES ?organization { UNDEF }\n  ?o a/rdfs:subClassOf* c:organization ;\n     rdfs:label ?organization .\n  ?d a/rdfs:subClassOf* c:deal ;\n     r:for_organization ?o ;\n     p:is_closed false ;\n     rdfs:label ?deal .\n  OPTIONAL { ?d p:amount ?amount }\n  OPTIONAL { ?d p:currency ?currency }\n  OPTIONAL { ?d r:in_stage ?s . ?s a/rdfs:subClassOf* c:stage ; rdfs:label ?stage }\n}\nORDER BY ?organization DESC(?amount)\n"),
        StarterQuestion(id="crm-03", text="What is the open pipeline amount per pipeline and stage, in stage order?", sparql="PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX p: <https://littlebigbrain.com/p/>\nPREFIX r: <https://littlebigbrain.com/r/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n\nSELECT ?pipeline ?stage ?currency (COUNT(?d) AS ?deals) (SUM(?amount) AS ?open_amount) WHERE {\n  ?d a/rdfs:subClassOf* c:deal ;\n     p:is_closed false ;\n     p:amount ?amount ;\n     r:in_stage ?s .\n  OPTIONAL { ?d p:currency ?currency }\n  ?s a/rdfs:subClassOf* c:stage ;\n     rdfs:label ?stage ;\n     p:display_order ?order ;\n     r:in_pipeline ?pl .\n  ?pl a/rdfs:subClassOf* c:pipeline ;\n      rdfs:label ?pipeline .\n}\nGROUP BY ?pipeline ?stage ?order ?currency\nORDER BY ?pipeline ?order ?currency\n"),
        StarterQuestion(id="crm-04", text="Which deals are expected to close this quarter, and who owns them?", sparql="PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX p: <https://littlebigbrain.com/p/>\nPREFIX r: <https://littlebigbrain.com/r/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n\nSELECT ?deal ?close_date ?amount ?currency ?owner WHERE {\n  ?d a/rdfs:subClassOf* c:deal ;\n     rdfs:label ?deal ;\n     p:is_closed false ;\n     p:close_date ?close_date .\n  # This quarter: the year and the quarter of today.\n  FILTER(YEAR(?close_date) = YEAR(NOW())\n         && CEIL(MONTH(?close_date) / 3) = CEIL(MONTH(NOW()) / 3))\n  OPTIONAL { ?d p:amount ?amount }\n  OPTIONAL { ?d p:currency ?currency }\n  OPTIONAL { ?d r:owned_by ?u . ?u a/rdfs:subClassOf* c:user ; rdfs:label ?owner }\n}\nORDER BY ?close_date\n"),
        StarterQuestion(id="crm-05", text="Which deals were won or lost in a period, and why were the lost ones lost?", sparql="PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX p: <https://littlebigbrain.com/p/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\nPREFIX xsd: <http://www.w3.org/2001/XMLSchema#>\n\nSELECT ?deal ?close_date ?won ?lost_reason WHERE {\n  # Inputs: the period's first instant and the instant after it, as\n  # xsd:dateTime. UNDEF leaves that end open.\n  VALUES (?from ?to) { (UNDEF UNDEF) }\n  ?d a/rdfs:subClassOf* c:deal ;\n     rdfs:label ?deal ;\n     p:is_closed true ;\n     p:is_won ?won ;\n     p:close_date ?close_date .\n  FILTER(!BOUND(?from) || ?close_date >= ?from)\n  FILTER(!BOUND(?to) || ?close_date < ?to)\n  OPTIONAL { ?d p:lost_reason ?lost_reason }\n}\nORDER BY ?close_date\n"),
        StarterQuestion(id="crm-06", text="Who are the people involved in a deal, and what are their job titles?", sparql="PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX p: <https://littlebigbrain.com/p/>\nPREFIX r: <https://littlebigbrain.com/r/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n\nSELECT ?deal ?person ?job_title WHERE {\n  # Input: a deal's name. UNDEF answers for every deal.\n  VALUES ?deal { UNDEF }\n  ?d a/rdfs:subClassOf* c:deal ;\n     rdfs:label ?deal ;\n     r:involves ?x .\n  ?x a/rdfs:subClassOf* c:person ;\n     rdfs:label ?person .\n  OPTIONAL { ?x p:job_title ?job_title }\n}\nORDER BY ?deal ?person\n"),
        StarterQuestion(id="crm-07", text="What calls, emails and meetings happened with an organization in the last 30 days?", sparql="PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX p: <https://littlebigbrain.com/p/>\nPREFIX r: <https://littlebigbrain.com/r/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\nPREFIX xsd: <http://www.w3.org/2001/XMLSchema#>\n\nSELECT ?organization ?activity ?kind ?occurred_at WHERE {\n  # Inputs: an organization's name, and the start of the window (30 days\n  # ago) as xsd:dateTime. UNDEF answers for every organization or date.\n  VALUES (?organization ?since) { (UNDEF UNDEF) }\n  ?o a/rdfs:subClassOf* c:organization ;\n     rdfs:label ?organization .\n  ?a a/rdfs:subClassOf* c:activity ;\n     r:about ?o ;\n     rdfs:label ?activity ;\n     p:occurred_at ?occurred_at ;\n     a ?type .\n  VALUES (?type ?kind) { (c:call \"call\") (c:email \"email\") (c:meeting \"meeting\") }\n  FILTER(!BOUND(?since) || ?occurred_at >= ?since)\n  FILTER(?occurred_at <= NOW())\n}\nORDER BY ?organization DESC(?occurred_at)\n"),
        StarterQuestion(id="crm-08", text="When was the last activity with a person, and what kind was it?", sparql="PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX p: <https://littlebigbrain.com/p/>\nPREFIX r: <https://littlebigbrain.com/r/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n\nSELECT ?person ?activity ?kind ?occurred_at WHERE {\n  # Input: a person's name. UNDEF answers for every person.\n  VALUES ?person { UNDEF }\n  ?x a/rdfs:subClassOf* c:person ;\n     rdfs:label ?person .\n  {\n    SELECT ?x (MAX(?at) AS ?occurred_at) WHERE {\n      ?any a/rdfs:subClassOf* c:activity ;\n           r:about ?x ;\n           p:occurred_at ?at .\n      FILTER(?at <= NOW())\n    }\n    GROUP BY ?x\n  }\n  ?a a/rdfs:subClassOf* c:activity ;\n     r:about ?x ;\n     p:occurred_at ?occurred_at ;\n     rdfs:label ?activity ;\n     a ?type .\n  ?type rdfs:subClassOf+ c:activity .\n  BIND(STRAFTER(STR(?type), \"/class/\") AS ?kind)\n}\nORDER BY ?person\n"),
        StarterQuestion(id="crm-09", text="Which open tickets does an organization have, by priority and stage?", sparql="PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX p: <https://littlebigbrain.com/p/>\nPREFIX r: <https://littlebigbrain.com/r/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n\nSELECT ?organization ?ticket ?priority ?stage WHERE {\n  # Input: an organization's name. UNDEF answers for every organization.\n  VALUES ?organization { UNDEF }\n  ?o a/rdfs:subClassOf* c:organization ;\n     rdfs:label ?organization .\n  ?t a/rdfs:subClassOf* c:ticket ;\n     r:for_organization ?o ;\n     p:is_closed false ;\n     rdfs:label ?ticket .\n  OPTIONAL { ?t p:priority ?priority }\n  OPTIONAL { ?t r:in_stage ?s . ?s a/rdfs:subClassOf* c:stage ; rdfs:label ?stage }\n}\nORDER BY ?organization ?priority ?stage\n"),
        StarterQuestion(id="crm-10", text="Which users own the most open deals and tickets?", sparql="PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX p: <https://littlebigbrain.com/p/>\nPREFIX r: <https://littlebigbrain.com/r/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n\nSELECT ?owner (COUNT(?record) AS ?open_records) WHERE {\n  { ?record a/rdfs:subClassOf* c:deal } UNION { ?record a/rdfs:subClassOf* c:ticket }\n  ?record p:is_closed false ;\n          r:owned_by ?u .\n  ?u a/rdfs:subClassOf* c:user ;\n     rdfs:label ?owner .\n}\nGROUP BY ?owner\nORDER BY DESC(?open_records) ?owner\n"),
        StarterQuestion(id="crm-11", text="Which teams does a user belong to, and is the user active?", sparql="PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX p: <https://littlebigbrain.com/p/>\nPREFIX r: <https://littlebigbrain.com/r/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n\nSELECT ?user ?is_active ?team WHERE {\n  # Input: a user's name. UNDEF answers for every user.\n  VALUES ?user { UNDEF }\n  ?u a/rdfs:subClassOf* c:user ;\n     rdfs:label ?user .\n  OPTIONAL { ?u p:is_active ?is_active }\n  OPTIONAL { ?u r:member_of ?t . ?t a/rdfs:subClassOf* c:team ; rdfs:label ?team }\n}\nORDER BY ?user ?team\n"),
        StarterQuestion(id="crm-12", text="Which products does a deal sell, with quantity and price?", sparql="PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX p: <https://littlebigbrain.com/p/>\nPREFIX r: <https://littlebigbrain.com/r/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n\nSELECT ?deal ?product ?sku ?quantity ?unit_price ?amount WHERE {\n  # Input: a deal's name. UNDEF answers for every deal.\n  VALUES ?deal { UNDEF }\n  ?d a/rdfs:subClassOf* c:deal ;\n     rdfs:label ?deal ;\n     r:has_line_item ?line .\n  ?line a/rdfs:subClassOf* c:lineitem .\n  OPTIONAL { ?line p:quantity ?quantity }\n  OPTIONAL { ?line p:unit_price ?unit_price }\n  OPTIONAL { ?line p:amount ?amount }\n  OPTIONAL {\n    ?line r:for_product ?pr .\n    ?pr a/rdfs:subClassOf* c:product ;\n        rdfs:label ?product .\n    OPTIONAL { ?pr p:sku ?sku }\n  }\n}\nORDER BY ?deal ?product\n"),
        StarterQuestion(id="crm-13", text="Which quotes exist for a deal, and when do they expire?", sparql="PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX p: <https://littlebigbrain.com/p/>\nPREFIX r: <https://littlebigbrain.com/r/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n\nSELECT ?deal ?quote ?status ?amount ?currency ?expires_at WHERE {\n  # Input: a deal's name. UNDEF answers for every deal.\n  VALUES ?deal { UNDEF }\n  ?d a/rdfs:subClassOf* c:deal ;\n     rdfs:label ?deal .\n  ?q a/rdfs:subClassOf* c:quote ;\n     r:quote_for ?d ;\n     rdfs:label ?quote .\n  OPTIONAL { ?q p:status ?status }\n  OPTIONAL { ?q p:amount ?amount }\n  OPTIONAL { ?q p:currency ?currency }\n  OPTIONAL { ?q p:expires_at ?expires_at }\n}\nORDER BY ?deal ?expires_at\n"),
        StarterQuestion(id="crm-14", text="Which organizations belong to a parent organization, directly or indirectly?", sparql="PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX p: <https://littlebigbrain.com/p/>\nPREFIX r: <https://littlebigbrain.com/r/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n\nSELECT ?parent ?organization ?domain ?direct_parent WHERE {\n  # Input: the parent organization's name. UNDEF answers for every parent.\n  VALUES ?parent { UNDEF }\n  ?top a/rdfs:subClassOf* c:organization ;\n       rdfs:label ?parent .\n  # Directly or indirectly: one or more SUBSIDIARY_OF steps.\n  ?o r:subsidiary_of+ ?top ;\n     rdfs:label ?organization ;\n     r:subsidiary_of ?up .\n  ?up rdfs:label ?direct_parent .\n  OPTIONAL { ?o p:domain ?domain }\n}\nORDER BY ?parent ?organization\n"),
        StarterQuestion(id="crm-15", text="Which leads came from a campaign, and which of them converted to deals?", sparql="PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX p: <https://littlebigbrain.com/p/>\nPREFIX r: <https://littlebigbrain.com/r/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n\nSELECT ?campaign ?campaign_start ?lead ?lead_source ?converted_deal WHERE {\n  # Input: a campaign's name. UNDEF answers for every campaign.\n  VALUES ?campaign { UNDEF }\n  ?k a/rdfs:subClassOf* c:campaign ;\n     rdfs:label ?campaign .\n  OPTIONAL { ?k p:start_at ?campaign_start }\n  ?l a/rdfs:subClassOf* c:lead ;\n     r:in_campaign ?k ;\n     rdfs:label ?lead .\n  OPTIONAL { ?l p:lead_source ?lead_source }\n  OPTIONAL {\n    ?l r:converted_to ?d .\n    ?d a/rdfs:subClassOf* c:deal ;\n       rdfs:label ?converted_deal .\n  }\n}\nORDER BY ?campaign ?lead\n"),
        StarterQuestion(id="crm-16", text="Who reports to a given person?", sparql="PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX p: <https://littlebigbrain.com/p/>\nPREFIX r: <https://littlebigbrain.com/r/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n\nSELECT ?manager ?person ?job_title WHERE {\n  # Input: the manager's name. UNDEF answers for every manager.\n  VALUES ?manager { UNDEF }\n  ?m a/rdfs:subClassOf* c:person ;\n     rdfs:label ?manager .\n  ?x r:reports_to ?m ;\n     rdfs:label ?person .\n  OPTIONAL { ?x p:job_title ?job_title }\n}\nORDER BY ?manager ?person\n"),
        StarterQuestion(id="crm-17", text="Which organizations are in an industry and country, with their size and revenue?", sparql="PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX p: <https://littlebigbrain.com/p/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n\nSELECT ?organization ?industry ?country ?employee_count ?annual_revenue WHERE {\n  # Inputs: an industry and a country. UNDEF answers for every industry or\n  # country.\n  VALUES (?industry ?country) { (UNDEF UNDEF) }\n  ?o a/rdfs:subClassOf* c:organization ;\n     rdfs:label ?organization ;\n     p:industry ?industry ;\n     p:country ?country .\n  OPTIONAL { ?o p:employee_count ?employee_count }\n  OPTIONAL { ?o p:annual_revenue ?annual_revenue }\n}\nORDER BY DESC(?annual_revenue)\n"),
        StarterQuestion(id="crm-18", text="What lifecycle stage and lead status does an organization or person have?", sparql="PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX p: <https://littlebigbrain.com/p/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n\nSELECT ?party ?kind ?lifecycle_stage ?lead_status WHERE {\n  # Input: the name of an organization or a person. UNDEF answers for every\n  # one.\n  VALUES ?party { UNDEF }\n  ?x a/rdfs:subClassOf* c:party ;\n     rdfs:label ?party .\n  { ?x a/rdfs:subClassOf* c:organization BIND(\"organization\" AS ?kind) }\n  UNION\n  { ?x a/rdfs:subClassOf* c:person BIND(\"person\" AS ?kind) }\n  OPTIONAL { ?x p:lifecycle_stage ?lifecycle_stage }\n  OPTIONAL { ?x p:lead_status ?lead_status }\n}\nORDER BY ?kind ?party\n"),
        StarterQuestion(id="crm-19", text="Which open deals have had no activity in 30 days?", sparql="PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX p: <https://littlebigbrain.com/p/>\nPREFIX r: <https://littlebigbrain.com/r/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\nPREFIX xsd: <http://www.w3.org/2001/XMLSchema#>\n\nSELECT ?deal ?owner WHERE {\n  # Input: the start of the window (30 days ago) as xsd:dateTime. UNDEF\n  # finds the open deals with no activity at all.\n  VALUES ?since { UNDEF }\n  ?d a/rdfs:subClassOf* c:deal ;\n     rdfs:label ?deal ;\n     p:is_closed false .\n  FILTER NOT EXISTS {\n    ?a a/rdfs:subClassOf* c:activity ;\n       r:about ?d ;\n       p:occurred_at ?at .\n    FILTER(!BOUND(?since) || ?at >= ?since)\n  }\n  OPTIONAL { ?d r:owned_by ?u . ?u rdfs:label ?owner }\n}\nORDER BY ?deal\n"),
        StarterQuestion(id="crm-20", text="Which tasks are overdue, on which records, and who does them?", sparql="PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX p: <https://littlebigbrain.com/p/>\nPREFIX r: <https://littlebigbrain.com/r/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n\nSELECT ?task ?status ?due_at ?record ?assignee WHERE {\n  ?t a/rdfs:subClassOf* c:task ;\n     rdfs:label ?task ;\n     p:due_at ?due_at .\n  # Overdue: due before now and not done.\n  FILTER(?due_at < NOW())\n  FILTER NOT EXISTS { ?t p:completed_at ?completed_at }\n  OPTIONAL { ?t p:status ?status }\n  OPTIONAL { ?t r:about ?x . ?x rdfs:label ?record }\n  OPTIONAL { ?t r:assigned_to ?u . ?u rdfs:label ?assignee }\n}\nORDER BY ?due_at\n"),
        StarterQuestion(id="crm-21", text="Which meetings are set for next week, and with whom?", sparql="PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX p: <https://littlebigbrain.com/p/>\nPREFIX r: <https://littlebigbrain.com/r/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\nPREFIX xsd: <http://www.w3.org/2001/XMLSchema#>\n\nSELECT ?meeting ?start_at ?end_at ?location ?person WHERE {\n  # Inputs: the window's first instant and the instant after it, as\n  # xsd:dateTime (next Monday and the Monday after). UNDEF reads from now on.\n  VALUES (?from ?to) { (UNDEF UNDEF) }\n  ?m a/rdfs:subClassOf* c:meeting ;\n     rdfs:label ?meeting ;\n     p:start_at ?start_at .\n  FILTER(?start_at >= COALESCE(?from, NOW()))\n  FILTER(!BOUND(?to) || ?start_at < ?to)\n  OPTIONAL { ?m p:end_at ?end_at }\n  OPTIONAL { ?m p:location ?location }\n  OPTIONAL { ?m r:about ?x . ?x a/rdfs:subClassOf* c:person ; rdfs:label ?person }\n}\nORDER BY ?start_at ?person\n"),
        StarterQuestion(id="crm-22", text="What is each owner's win rate: won deals out of closed deals?", sparql="PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX p: <https://littlebigbrain.com/p/>\nPREFIX r: <https://littlebigbrain.com/r/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n\nSELECT ?owner (SUM(IF(?won, 1, 0)) AS ?won_deals) (COUNT(?d) AS ?closed_deals)\n       (SUM(IF(?won, 1, 0)) / COUNT(?d) AS ?win_rate) WHERE {\n  ?d a/rdfs:subClassOf* c:deal ;\n     p:is_closed true ;\n     p:is_won ?won ;\n     r:owned_by ?u .\n  ?u a/rdfs:subClassOf* c:user ;\n     rdfs:label ?owner .\n}\nGROUP BY ?owner\nORDER BY DESC(?win_rate) ?owner\n"),
        StarterQuestion(id="crm-23", text="Which tickets involve a person, and through which channel did they come in?", sparql="PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX p: <https://littlebigbrain.com/p/>\nPREFIX r: <https://littlebigbrain.com/r/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n\nSELECT ?person ?ticket ?channel ?created_at WHERE {\n  # Input: a person's name. UNDEF answers for every person.\n  VALUES ?person { UNDEF }\n  ?x a/rdfs:subClassOf* c:person ;\n     rdfs:label ?person .\n  ?t a/rdfs:subClassOf* c:ticket ;\n     r:involves ?x ;\n     rdfs:label ?ticket .\n  OPTIONAL { ?t p:channel ?channel }\n  OPTIONAL { ?t p:created_at ?created_at }\n}\nORDER BY ?person ?created_at\n"),
        StarterQuestion(id="crm-24", text="Which organizations have both open tickets and open deals?", sparql="PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX p: <https://littlebigbrain.com/p/>\nPREFIX r: <https://littlebigbrain.com/r/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n\nSELECT ?organization WHERE {\n  ?o a/rdfs:subClassOf* c:organization ;\n     rdfs:label ?organization .\n  FILTER EXISTS {\n    ?t a/rdfs:subClassOf* c:ticket ; r:for_organization ?o ; p:is_closed false .\n  }\n  FILTER EXISTS {\n    ?d a/rdfs:subClassOf* c:deal ; r:for_organization ?o ; p:is_closed false .\n  }\n}\nORDER BY ?organization\n"),
        StarterQuestion(id="crm-25", text="Where does a record come from: which system, which id, which link?", sparql="PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX p: <https://littlebigbrain.com/p/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n\nSELECT ?record ?kind ?source_system ?source_id ?source_url ?source_updated_at WHERE {\n  # Input: a record's name. UNDEF answers for every organization and person.\n  VALUES ?record { UNDEF }\n  { ?x a/rdfs:subClassOf* c:organization BIND(\"organization\" AS ?kind) }\n  UNION\n  { ?x a/rdfs:subClassOf* c:person BIND(\"person\" AS ?kind) }\n  ?x rdfs:label ?record ;\n     p:source_system ?source_system .\n  OPTIONAL { ?x p:source_id ?source_id }\n  OPTIONAL { ?x p:source_url ?source_url }\n  OPTIONAL { ?x p:source_updated_at ?source_updated_at }\n}\nORDER BY ?kind ?record\n"),
        StarterQuestion(id="crm-26", text="Which notes were written on a deal, and when?", sparql="PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX p: <https://littlebigbrain.com/p/>\nPREFIX r: <https://littlebigbrain.com/r/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n\nSELECT ?deal ?note ?created_at ?text WHERE {\n  # Input: a deal's name. UNDEF answers for every deal.\n  VALUES ?deal { UNDEF }\n  ?d a/rdfs:subClassOf* c:deal ;\n     rdfs:label ?deal .\n  ?n a/rdfs:subClassOf* c:note ;\n     r:about ?d ;\n     rdfs:label ?note .\n  OPTIONAL { ?n p:created_at ?created_at }\n  OPTIONAL { ?n p:text ?text }\n}\nORDER BY ?deal DESC(?created_at)\n"),
        StarterQuestion(id="crm-27", text="How many calls did each user make, with what outcomes and how long?", sparql="PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX p: <https://littlebigbrain.com/p/>\nPREFIX r: <https://littlebigbrain.com/r/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n\nSELECT ?user ?direction ?outcome (COUNT(?call) AS ?calls) (SUM(?seconds) AS ?total_seconds) WHERE {\n  ?call a/rdfs:subClassOf* c:call ;\n        r:owned_by ?u .\n  ?u a/rdfs:subClassOf* c:user ;\n     rdfs:label ?user .\n  OPTIONAL { ?call p:direction ?direction }\n  OPTIONAL { ?call p:outcome ?outcome }\n  OPTIONAL { ?call p:duration_seconds ?seconds }\n}\nGROUP BY ?user ?direction ?outcome\nORDER BY ?user ?direction ?outcome\n"),
        StarterQuestion(id="crm-28", text="Which emails were exchanged with a person?", sparql="PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX p: <https://littlebigbrain.com/p/>\nPREFIX r: <https://littlebigbrain.com/r/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n\nSELECT ?person ?email ?from_address ?to_address ?occurred_at WHERE {\n  # Input: a person's name. UNDEF answers for every person.\n  VALUES ?person { UNDEF }\n  ?x a/rdfs:subClassOf* c:person ;\n     rdfs:label ?person .\n  ?m a/rdfs:subClassOf* c:email ;\n     r:about ?x ;\n     rdfs:label ?email .\n  OPTIONAL { ?m p:from_address ?from_address }\n  OPTIONAL { ?m p:to_addresses ?to_address }\n  OPTIONAL { ?m p:occurred_at ?occurred_at }\n}\nORDER BY ?person DESC(?occurred_at)\n"),
        StarterQuestion(id="crm-29", text="Which campaigns are running, with their budget and members?", sparql="PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX p: <https://littlebigbrain.com/p/>\nPREFIX r: <https://littlebigbrain.com/r/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n\nSELECT ?campaign ?status ?start_at ?end_at ?budget ?member WHERE {\n  ?k a/rdfs:subClassOf* c:campaign ;\n     rdfs:label ?campaign ;\n     p:start_at ?start_at ;\n     p:end_at ?end_at .\n  # Running: started and not ended.\n  FILTER(?start_at <= NOW() && ?end_at >= NOW())\n  OPTIONAL { ?k p:status ?status }\n  OPTIONAL { ?k p:budget ?budget }\n  OPTIONAL {\n    ?m r:in_campaign ?k ;\n       a/rdfs:subClassOf* c:person ;\n       rdfs:label ?member .\n  }\n}\nORDER BY ?campaign ?member\n"),
        StarterQuestion(id="crm-30", text="What does the product catalog sell, and at what price?", sparql="PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX p: <https://littlebigbrain.com/p/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n\nSELECT ?product ?sku ?unit_price ?currency WHERE {\n  ?x a/rdfs:subClassOf* c:product ;\n     rdfs:label ?product ;\n     p:is_active true .\n  OPTIONAL { ?x p:sku ?sku }\n  OPTIONAL { ?x p:unit_price ?unit_price }\n  OPTIONAL { ?x p:currency ?currency }\n}\nORDER BY ?product\n"),
    )


crm = _Crm()


class _DocumentsClasses:
    Party = StarterClass(name="Party", iri="https://littlebigbrain.com/class/party", super_types=())
    Person = StarterClass(name="Person", iri="https://littlebigbrain.com/class/person", super_types=("Party",))
    User = StarterClass(name="User", iri="https://littlebigbrain.com/class/user", super_types=("Person",))
    Tag = StarterClass(name="Tag", iri="https://littlebigbrain.com/class/tag", super_types=())
    Site = StarterClass(name="Site", iri="https://littlebigbrain.com/class/site", super_types=())
    Library = StarterClass(name="Library", iri="https://littlebigbrain.com/class/library", super_types=())
    Folder = StarterClass(name="Folder", iri="https://littlebigbrain.com/class/folder", super_types=())
    Document = StarterClass(name="Document", iri="https://littlebigbrain.com/class/document", super_types=())
    Page = StarterClass(name="Page", iri="https://littlebigbrain.com/class/page", super_types=("Document",))


class _DocumentsProperties:
    source_system = StarterProperty(name="source_system", iri="https://littlebigbrain.com/p/source_system", value_type="keyword")
    source_id = StarterProperty(name="source_id", iri="https://littlebigbrain.com/p/source_id", value_type="keyword")
    source_url = StarterProperty(name="source_url", iri="https://littlebigbrain.com/p/source_url", value_type="keyword")
    source_updated_at = StarterProperty(name="source_updated_at", iri="https://littlebigbrain.com/p/source_updated_at", value_type="date_time")
    source_key = StarterProperty(name="source_key", iri="https://littlebigbrain.com/p/source_key", value_type="keyword")
    text = StarterProperty(name="text", iri="https://littlebigbrain.com/p/text", value_type="text")
    acl = StarterProperty(name="acl", iri="https://littlebigbrain.com/p/acl", value_type="keyword_set")
    created_at = StarterProperty(name="created_at", iri="https://littlebigbrain.com/p/created_at", value_type="date_time")
    modified_at = StarterProperty(name="modified_at", iri="https://littlebigbrain.com/p/modified_at", value_type="date_time")
    description = StarterProperty(name="description", iri="https://littlebigbrain.com/p/description", value_type="text")
    phone = StarterProperty(name="phone", iri="https://littlebigbrain.com/p/phone", value_type="keyword")
    website = StarterProperty(name="website", iri="https://littlebigbrain.com/p/website", value_type="keyword")
    street_address = StarterProperty(name="street_address", iri="https://littlebigbrain.com/p/street_address", value_type="keyword")
    city = StarterProperty(name="city", iri="https://littlebigbrain.com/p/city", value_type="keyword")
    region = StarterProperty(name="region", iri="https://littlebigbrain.com/p/region", value_type="keyword")
    postal_code = StarterProperty(name="postal_code", iri="https://littlebigbrain.com/p/postal_code", value_type="keyword")
    country = StarterProperty(name="country", iri="https://littlebigbrain.com/p/country", value_type="keyword")
    linkedin_url = StarterProperty(name="linkedin_url", iri="https://littlebigbrain.com/p/linkedin_url", value_type="keyword")
    lifecycle_stage = StarterProperty(name="lifecycle_stage", iri="https://littlebigbrain.com/p/lifecycle_stage", value_type="keyword")
    first_name = StarterProperty(name="first_name", iri="https://littlebigbrain.com/p/first_name", value_type="keyword")
    last_name = StarterProperty(name="last_name", iri="https://littlebigbrain.com/p/last_name", value_type="keyword")
    email = StarterProperty(name="email", iri="https://littlebigbrain.com/p/email", value_type="keyword")
    job_title = StarterProperty(name="job_title", iri="https://littlebigbrain.com/p/job_title", value_type="keyword")
    mobile_phone = StarterProperty(name="mobile_phone", iri="https://littlebigbrain.com/p/mobile_phone", value_type="keyword")
    company_name = StarterProperty(name="company_name", iri="https://littlebigbrain.com/p/company_name", value_type="keyword")
    lead_status = StarterProperty(name="lead_status", iri="https://littlebigbrain.com/p/lead_status", value_type="keyword")
    is_active = StarterProperty(name="is_active", iri="https://littlebigbrain.com/p/is_active", value_type="bool")
    file_extension = StarterProperty(name="file_extension", iri="https://littlebigbrain.com/p/file_extension", value_type="keyword")
    mime_type = StarterProperty(name="mime_type", iri="https://littlebigbrain.com/p/mime_type", value_type="keyword")
    size_bytes = StarterProperty(name="size_bytes", iri="https://littlebigbrain.com/p/size_bytes", value_type="i64")
    content_hash = StarterProperty(name="content_hash", iri="https://littlebigbrain.com/p/content_hash", value_type="keyword")
    version_label = StarterProperty(name="version_label", iri="https://littlebigbrain.com/p/version_label", value_type="keyword")
    document_type = StarterProperty(name="document_type", iri="https://littlebigbrain.com/p/document_type", value_type="keyword")
    language = StarterProperty(name="language", iri="https://littlebigbrain.com/p/language", value_type="keyword")
    page_count = StarterProperty(name="page_count", iri="https://littlebigbrain.com/p/page_count", value_type="i64")
    path = StarterProperty(name="path", iri="https://littlebigbrain.com/p/path", value_type="keyword")
    sensitivity_label = StarterProperty(name="sensitivity_label", iri="https://littlebigbrain.com/p/sensitivity_label", value_type="keyword")
    item_count = StarterProperty(name="item_count", iri="https://littlebigbrain.com/p/item_count", value_type="i64")


class _DocumentsRelations:
    IN_SITE = StarterRelation(name="IN_SITE", iri="https://littlebigbrain.com/r/in_site", domain=("Library", "Page"), range=("Site",), cardinality="many_to_one", inverse="SITE_HOLDS", inverse_iri="https://littlebigbrain.com/r/site_holds")
    IN_LIBRARY = StarterRelation(name="IN_LIBRARY", iri="https://littlebigbrain.com/r/in_library", domain=("Folder", "Document"), range=("Library",), cardinality="many_to_one", inverse="LIBRARY_HOLDS", inverse_iri="https://littlebigbrain.com/r/library_holds")
    IN_FOLDER = StarterRelation(name="IN_FOLDER", iri="https://littlebigbrain.com/r/in_folder", domain=("Folder", "Document"), range=("Folder",), cardinality="many_to_one", inverse="FOLDER_HOLDS", inverse_iri="https://littlebigbrain.com/r/folder_holds")
    CREATED_BY = StarterRelation(name="CREATED_BY", iri="https://littlebigbrain.com/r/created_by", domain=("Document", "Folder"), range=("User",), cardinality="many_to_one", inverse="CREATOR_OF", inverse_iri="https://littlebigbrain.com/r/creator_of")
    MODIFIED_BY = StarterRelation(name="MODIFIED_BY", iri="https://littlebigbrain.com/r/modified_by", domain=("Document", "Folder"), range=("User",), cardinality="many_to_one", inverse="LAST_MODIFIED", inverse_iri="https://littlebigbrain.com/r/last_modified")
    TAGGED_WITH = StarterRelation(name="TAGGED_WITH", iri="https://littlebigbrain.com/r/tagged_with", domain=("Document",), range=("Tag",), cardinality="many_to_many", inverse="TAGS", inverse_iri="https://littlebigbrain.com/r/tags")
    BROADER = StarterRelation(name="BROADER", iri="https://littlebigbrain.com/r/broader", domain=("Tag",), range=("Tag",), cardinality="many_to_many", inverse="NARROWER", inverse_iri="https://littlebigbrain.com/r/narrower")
    LINKS_TO = StarterRelation(name="LINKS_TO", iri="https://littlebigbrain.com/r/links_to", domain=("Document",), range=("Document",), cardinality="many_to_many", inverse="LINKED_FROM", inverse_iri="https://littlebigbrain.com/r/linked_from")


class _Documents:
    """The Documents starter 1.0.0."""

    id = "documents"
    version = "1.0.0"
    label = "Documents"
    classes = _DocumentsClasses
    properties = _DocumentsProperties
    relations = _DocumentsRelations
    questions: tuple[StarterQuestion, ...] = (
        StarterQuestion(id="doc-01", text="Which documents are in a folder, and how big are they?", sparql="PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX p: <https://littlebigbrain.com/p/>\nPREFIX r: <https://littlebigbrain.com/r/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n\nSELECT ?folder ?document ?size_bytes ?file_extension WHERE {\n  # Input: a folder's name. UNDEF answers for every folder.\n  VALUES ?folder { UNDEF }\n  ?f a/rdfs:subClassOf* c:folder ;\n     rdfs:label ?folder .\n  ?d a/rdfs:subClassOf* c:document ;\n     r:in_folder ?f ;\n     rdfs:label ?document .\n  OPTIONAL { ?d p:size_bytes ?size_bytes }\n  OPTIONAL { ?d p:file_extension ?file_extension }\n}\nORDER BY ?folder DESC(?size_bytes)\n"),
        StarterQuestion(id="doc-02", text="Which documents in a library changed last week, and who changed them?", sparql="PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX p: <https://littlebigbrain.com/p/>\nPREFIX r: <https://littlebigbrain.com/r/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\nPREFIX xsd: <http://www.w3.org/2001/XMLSchema#>\n\nSELECT ?library ?document ?modified_at ?modified_by WHERE {\n  # Inputs: a library's name, and the start of the window (a week ago) as\n  # xsd:dateTime. UNDEF answers for every library or date.\n  VALUES (?library ?since) { (UNDEF UNDEF) }\n  ?l a/rdfs:subClassOf* c:library ;\n     rdfs:label ?library .\n  ?d a/rdfs:subClassOf* c:document ;\n     r:in_library ?l ;\n     rdfs:label ?document ;\n     p:modified_at ?modified_at .\n  FILTER(!BOUND(?since) || ?modified_at >= ?since)\n  OPTIONAL {\n    ?d r:modified_by ?u .\n    ?u a/rdfs:subClassOf* c:user ;\n       rdfs:label ?modified_by .\n  }\n}\nORDER BY ?library DESC(?modified_at)\n"),
        StarterQuestion(id="doc-03", text="Who created a document, and when?", sparql="PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX p: <https://littlebigbrain.com/p/>\nPREFIX r: <https://littlebigbrain.com/r/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n\nSELECT ?document ?created_at ?created_by WHERE {\n  # Input: a document's name. UNDEF answers for every document.\n  VALUES ?document { UNDEF }\n  ?d a/rdfs:subClassOf* c:document ;\n     rdfs:label ?document .\n  OPTIONAL { ?d p:created_at ?created_at }\n  OPTIONAL {\n    ?d r:created_by ?u .\n    ?u a/rdfs:subClassOf* c:user ;\n       rdfs:label ?created_by .\n  }\n}\nORDER BY ?document\n"),
        StarterQuestion(id="doc-04", text="Which libraries and pages does a site hold?", sparql="PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX r: <https://littlebigbrain.com/r/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n\nSELECT ?site ?kind ?item WHERE {\n  # Input: a site's name. UNDEF answers for every site.\n  VALUES ?site { UNDEF }\n  ?s a/rdfs:subClassOf* c:site ;\n     rdfs:label ?site .\n  ?x r:in_site ?s ;\n     rdfs:label ?item .\n  { ?x a/rdfs:subClassOf* c:library BIND(\"library\" AS ?kind) }\n  UNION\n  { ?x a/rdfs:subClassOf* c:page BIND(\"page\" AS ?kind) }\n}\nORDER BY ?site ?kind ?item\n"),
        StarterQuestion(id="doc-05", text="Where is a document: its folders up to its library and site?", sparql="PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX p: <https://littlebigbrain.com/p/>\nPREFIX r: <https://littlebigbrain.com/r/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n\nSELECT ?document ?path ?folder ?library ?site WHERE {\n  # Input: a document's name. UNDEF answers for every document.\n  VALUES ?document { UNDEF }\n  ?d a/rdfs:subClassOf* c:document ;\n     rdfs:label ?document .\n  OPTIONAL { ?d p:path ?path }\n  # Every folder up the path: one or more IN_FOLDER steps.\n  OPTIONAL {\n    ?d r:in_folder+ ?f .\n    ?f a/rdfs:subClassOf* c:folder ;\n       rdfs:label ?folder .\n  }\n  OPTIONAL {\n    ?d r:in_library ?l .\n    ?l a/rdfs:subClassOf* c:library ;\n       rdfs:label ?library .\n    OPTIONAL {\n      ?l r:in_site ?s .\n      ?s a/rdfs:subClassOf* c:site ;\n         rdfs:label ?site .\n    }\n  }\n}\nORDER BY ?document ?folder\n"),
        StarterQuestion(id="doc-06", text="Which documents carry a tag, or a narrower tag?", sparql="PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX r: <https://littlebigbrain.com/r/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n\nSELECT ?tag ?document ?tagged_with WHERE {\n  # Input: a tag's name. UNDEF answers for every tag.\n  VALUES ?tag { UNDEF }\n  ?t a/rdfs:subClassOf* c:tag ;\n     rdfs:label ?tag .\n  ?d a/rdfs:subClassOf* c:document ;\n     rdfs:label ?document ;\n     r:tagged_with ?direct .\n  # The tag itself or a narrower one: zero or more BROADER steps.\n  ?direct r:broader* ?t ;\n          rdfs:label ?tagged_with .\n}\nORDER BY ?tag ?document\n"),
        StarterQuestion(id="doc-07", text="Which documents are of a given type, such as contracts or policies?", sparql="PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX p: <https://littlebigbrain.com/p/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n\nSELECT ?document_type ?document WHERE {\n  # Input: a document type, such as Contract. UNDEF answers for every type.\n  VALUES ?document_type { UNDEF }\n  ?d a/rdfs:subClassOf* c:document ;\n     rdfs:label ?document ;\n     p:document_type ?document_type .\n}\nORDER BY ?document_type ?document\n"),
        StarterQuestion(id="doc-08", text="Which documents may a given person or group read?", sparql="PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX p: <https://littlebigbrain.com/p/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n\nSELECT DISTINCT ?document ?principal WHERE {\n  # Input: the principals of a person or a group as the source writes them:\n  # a user's own principal and those of its groups. UNDEF lists every reader.\n  VALUES ?principal { UNDEF }\n  ?d a/rdfs:subClassOf* c:document ;\n     rdfs:label ?document ;\n     p:acl ?principal .\n}\nORDER BY ?document ?principal\n"),
        StarterQuestion(id="doc-09", text="Which documents link to a given document?", sparql="PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX r: <https://littlebigbrain.com/r/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n\nSELECT ?target ?document WHERE {\n  # Input: the linked document's name. UNDEF answers for every document.\n  VALUES ?target { UNDEF }\n  ?t a/rdfs:subClassOf* c:document ;\n     rdfs:label ?target .\n  ?d a/rdfs:subClassOf* c:document ;\n     r:links_to ?t ;\n     rdfs:label ?document .\n}\nORDER BY ?target ?document\n"),
        StarterQuestion(id="doc-10", text="Which documents carry a sensitivity label, such as Confidential?", sparql="PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX p: <https://littlebigbrain.com/p/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n\nSELECT ?sensitivity_label ?document WHERE {\n  # Input: a sensitivity label, such as Confidential. UNDEF answers for\n  # every label.\n  VALUES ?sensitivity_label { UNDEF }\n  ?d a/rdfs:subClassOf* c:document ;\n     rdfs:label ?document ;\n     p:sensitivity_label ?sensitivity_label .\n}\nORDER BY ?sensitivity_label ?document\n"),
        StarterQuestion(id="doc-11", text="Which documents have the same content in more than one place?", sparql="PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX p: <https://littlebigbrain.com/p/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n\nSELECT ?content_hash ?document ?path WHERE {\n  ?d a/rdfs:subClassOf* c:document ;\n     rdfs:label ?document ;\n     p:content_hash ?content_hash .\n  OPTIONAL { ?d p:path ?path }\n  {\n    SELECT ?content_hash WHERE {\n      ?x a/rdfs:subClassOf* c:document ;\n         p:content_hash ?content_hash .\n    }\n    GROUP BY ?content_hash\n    HAVING (COUNT(?x) > 1)\n  }\n}\nORDER BY ?content_hash ?path\n"),
        StarterQuestion(id="doc-12", text="Which users changed the most documents in a library this month?", sparql="PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX p: <https://littlebigbrain.com/p/>\nPREFIX r: <https://littlebigbrain.com/r/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n\nSELECT ?library ?user (COUNT(?d) AS ?documents_changed) WHERE {\n  # Input: a library's name. UNDEF answers for every library.\n  VALUES ?library { UNDEF }\n  ?l a/rdfs:subClassOf* c:library ;\n     rdfs:label ?library .\n  ?d a/rdfs:subClassOf* c:document ;\n     r:in_library ?l ;\n     p:modified_at ?modified_at ;\n     r:modified_by ?u .\n  ?u a/rdfs:subClassOf* c:user ;\n     rdfs:label ?user .\n  # This month: the year and the month of today.\n  FILTER(YEAR(?modified_at) = YEAR(NOW()) && MONTH(?modified_at) = MONTH(NOW()))\n}\nGROUP BY ?library ?user\nORDER BY ?library DESC(?documents_changed) ?user\n"),
        StarterQuestion(id="doc-13", text="What file types does a library hold, by count and size?", sparql="PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX p: <https://littlebigbrain.com/p/>\nPREFIX r: <https://littlebigbrain.com/r/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n\nSELECT ?library ?file_extension ?mime_type (COUNT(?d) AS ?documents) (SUM(?size) AS ?size_bytes) WHERE {\n  ?d a/rdfs:subClassOf* c:document ;\n     r:in_library ?l ;\n     p:file_extension ?file_extension .\n  OPTIONAL { ?d p:mime_type ?mime_type }\n  OPTIONAL { ?d p:size_bytes ?size }\n  ?l a/rdfs:subClassOf* c:library ;\n     rdfs:label ?library .\n}\nGROUP BY ?library ?file_extension ?mime_type\nORDER BY ?library ?file_extension\n"),
        StarterQuestion(id="doc-14", text="Which documents are in a language, with how many pages?", sparql="PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX p: <https://littlebigbrain.com/p/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n\nSELECT ?language ?document ?page_count WHERE {\n  # Input: a language as a BCP 47 tag, such as de. UNDEF answers for every\n  # language.\n  VALUES ?language { UNDEF }\n  ?d a/rdfs:subClassOf* c:document ;\n     rdfs:label ?document ;\n     p:language ?language .\n  OPTIONAL { ?d p:page_count ?page_count }\n}\nORDER BY ?language ?document\n"),
        StarterQuestion(id="doc-15", text="Where does a document come from: which system, which id, which link, which version?", sparql="PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX p: <https://littlebigbrain.com/p/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n\nSELECT ?document ?source_system ?source_id ?source_url ?version_label WHERE {\n  # Input: a document's name. UNDEF answers for every document.\n  VALUES ?document { UNDEF }\n  ?d a/rdfs:subClassOf* c:document ;\n     rdfs:label ?document ;\n     p:source_system ?source_system .\n  OPTIONAL { ?d p:source_id ?source_id }\n  OPTIONAL { ?d p:source_url ?source_url }\n  OPTIONAL { ?d p:version_label ?version_label }\n}\nORDER BY ?document\n"),
        StarterQuestion(id="doc-16", text="Which people wrote documents in a site, and who are they?", sparql="PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX p: <https://littlebigbrain.com/p/>\nPREFIX r: <https://littlebigbrain.com/r/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n\nSELECT DISTINCT ?site ?person ?email ?job_title WHERE {\n  # Input: a site's name. UNDEF answers for every site.\n  VALUES ?site { UNDEF }\n  ?s a/rdfs:subClassOf* c:site ;\n     rdfs:label ?site .\n  ?d a/rdfs:subClassOf* c:document ;\n     r:created_by ?x .\n  # A file is in a library of the site; a page is in the site.\n  { ?d r:in_library/r:in_site ?s } UNION { ?d r:in_site ?s }\n  ?x a/rdfs:subClassOf* c:person ;\n     rdfs:label ?person .\n  OPTIONAL { ?x p:email ?email }\n  OPTIONAL { ?x p:job_title ?job_title }\n}\nORDER BY ?site ?person\n"),
    )


documents = _Documents()


class _WorkClasses:
    Party = StarterClass(name="Party", iri="https://littlebigbrain.com/class/party", super_types=())
    Organization = StarterClass(name="Organization", iri="https://littlebigbrain.com/class/organization", super_types=("Party",))
    Person = StarterClass(name="Person", iri="https://littlebigbrain.com/class/person", super_types=("Party",))
    User = StarterClass(name="User", iri="https://littlebigbrain.com/class/user", super_types=("Person",))
    Team = StarterClass(name="Team", iri="https://littlebigbrain.com/class/team", super_types=())
    Task = StarterClass(name="Task", iri="https://littlebigbrain.com/class/task", super_types=())
    Pipeline = StarterClass(name="Pipeline", iri="https://littlebigbrain.com/class/pipeline", super_types=())
    Stage = StarterClass(name="Stage", iri="https://littlebigbrain.com/class/stage", super_types=())
    Tag = StarterClass(name="Tag", iri="https://littlebigbrain.com/class/tag", super_types=())
    Issue = StarterClass(name="Issue", iri="https://littlebigbrain.com/class/issue", super_types=("Task",))
    Project = StarterClass(name="Project", iri="https://littlebigbrain.com/class/project", super_types=())
    Milestone = StarterClass(name="Milestone", iri="https://littlebigbrain.com/class/milestone", super_types=())
    Iteration = StarterClass(name="Iteration", iri="https://littlebigbrain.com/class/iteration", super_types=())
    Comment = StarterClass(name="Comment", iri="https://littlebigbrain.com/class/comment", super_types=())


class _WorkProperties:
    source_system = StarterProperty(name="source_system", iri="https://littlebigbrain.com/p/source_system", value_type="keyword")
    source_id = StarterProperty(name="source_id", iri="https://littlebigbrain.com/p/source_id", value_type="keyword")
    source_url = StarterProperty(name="source_url", iri="https://littlebigbrain.com/p/source_url", value_type="keyword")
    source_updated_at = StarterProperty(name="source_updated_at", iri="https://littlebigbrain.com/p/source_updated_at", value_type="date_time")
    source_key = StarterProperty(name="source_key", iri="https://littlebigbrain.com/p/source_key", value_type="keyword")
    text = StarterProperty(name="text", iri="https://littlebigbrain.com/p/text", value_type="text")
    acl = StarterProperty(name="acl", iri="https://littlebigbrain.com/p/acl", value_type="keyword_set")
    created_at = StarterProperty(name="created_at", iri="https://littlebigbrain.com/p/created_at", value_type="date_time")
    modified_at = StarterProperty(name="modified_at", iri="https://littlebigbrain.com/p/modified_at", value_type="date_time")
    description = StarterProperty(name="description", iri="https://littlebigbrain.com/p/description", value_type="text")
    phone = StarterProperty(name="phone", iri="https://littlebigbrain.com/p/phone", value_type="keyword")
    website = StarterProperty(name="website", iri="https://littlebigbrain.com/p/website", value_type="keyword")
    street_address = StarterProperty(name="street_address", iri="https://littlebigbrain.com/p/street_address", value_type="keyword")
    city = StarterProperty(name="city", iri="https://littlebigbrain.com/p/city", value_type="keyword")
    region = StarterProperty(name="region", iri="https://littlebigbrain.com/p/region", value_type="keyword")
    postal_code = StarterProperty(name="postal_code", iri="https://littlebigbrain.com/p/postal_code", value_type="keyword")
    country = StarterProperty(name="country", iri="https://littlebigbrain.com/p/country", value_type="keyword")
    linkedin_url = StarterProperty(name="linkedin_url", iri="https://littlebigbrain.com/p/linkedin_url", value_type="keyword")
    lifecycle_stage = StarterProperty(name="lifecycle_stage", iri="https://littlebigbrain.com/p/lifecycle_stage", value_type="keyword")
    domain = StarterProperty(name="domain", iri="https://littlebigbrain.com/p/domain", value_type="keyword")
    industry = StarterProperty(name="industry", iri="https://littlebigbrain.com/p/industry", value_type="keyword")
    annual_revenue = StarterProperty(name="annual_revenue", iri="https://littlebigbrain.com/p/annual_revenue", value_type="f64")
    employee_count = StarterProperty(name="employee_count", iri="https://littlebigbrain.com/p/employee_count", value_type="i64")
    company_type = StarterProperty(name="company_type", iri="https://littlebigbrain.com/p/company_type", value_type="keyword")
    first_name = StarterProperty(name="first_name", iri="https://littlebigbrain.com/p/first_name", value_type="keyword")
    last_name = StarterProperty(name="last_name", iri="https://littlebigbrain.com/p/last_name", value_type="keyword")
    email = StarterProperty(name="email", iri="https://littlebigbrain.com/p/email", value_type="keyword")
    job_title = StarterProperty(name="job_title", iri="https://littlebigbrain.com/p/job_title", value_type="keyword")
    mobile_phone = StarterProperty(name="mobile_phone", iri="https://littlebigbrain.com/p/mobile_phone", value_type="keyword")
    company_name = StarterProperty(name="company_name", iri="https://littlebigbrain.com/p/company_name", value_type="keyword")
    lead_status = StarterProperty(name="lead_status", iri="https://littlebigbrain.com/p/lead_status", value_type="keyword")
    is_active = StarterProperty(name="is_active", iri="https://littlebigbrain.com/p/is_active", value_type="bool")
    probability = StarterProperty(name="probability", iri="https://littlebigbrain.com/p/probability", value_type="f64")
    is_closed = StarterProperty(name="is_closed", iri="https://littlebigbrain.com/p/is_closed", value_type="bool")
    is_won = StarterProperty(name="is_won", iri="https://littlebigbrain.com/p/is_won", value_type="bool")
    object_type = StarterProperty(name="object_type", iri="https://littlebigbrain.com/p/object_type", value_type="keyword")
    display_order = StarterProperty(name="display_order", iri="https://littlebigbrain.com/p/display_order", value_type="i64")
    stage_category = StarterProperty(name="stage_category", iri="https://littlebigbrain.com/p/stage_category", value_type="keyword")
    priority = StarterProperty(name="priority", iri="https://littlebigbrain.com/p/priority", value_type="keyword")
    status = StarterProperty(name="status", iri="https://littlebigbrain.com/p/status", value_type="keyword")
    start_at = StarterProperty(name="start_at", iri="https://littlebigbrain.com/p/start_at", value_type="date_time")
    end_at = StarterProperty(name="end_at", iri="https://littlebigbrain.com/p/end_at", value_type="date_time")
    due_at = StarterProperty(name="due_at", iri="https://littlebigbrain.com/p/due_at", value_type="date_time")
    completed_at = StarterProperty(name="completed_at", iri="https://littlebigbrain.com/p/completed_at", value_type="date_time")
    identifier = StarterProperty(name="identifier", iri="https://littlebigbrain.com/p/identifier", value_type="keyword")
    issue_type = StarterProperty(name="issue_type", iri="https://littlebigbrain.com/p/issue_type", value_type="keyword")
    estimate = StarterProperty(name="estimate", iri="https://littlebigbrain.com/p/estimate", value_type="f64")
    started_at = StarterProperty(name="started_at", iri="https://littlebigbrain.com/p/started_at", value_type="date_time")
    canceled_at = StarterProperty(name="canceled_at", iri="https://littlebigbrain.com/p/canceled_at", value_type="date_time")
    target_date = StarterProperty(name="target_date", iri="https://littlebigbrain.com/p/target_date", value_type="date_time")
    progress = StarterProperty(name="progress", iri="https://littlebigbrain.com/p/progress", value_type="f64")
    health = StarterProperty(name="health", iri="https://littlebigbrain.com/p/health", value_type="keyword")
    number = StarterProperty(name="number", iri="https://littlebigbrain.com/p/number", value_type="i64")


class _WorkRelations:
    ASSIGNED_TO = StarterRelation(name="ASSIGNED_TO", iri="https://littlebigbrain.com/r/assigned_to", domain=("Task",), range=("User",), cardinality="many_to_one", inverse="ASSIGNEE_OF", inverse_iri="https://littlebigbrain.com/r/assignee_of")
    CREATED_BY = StarterRelation(name="CREATED_BY", iri="https://littlebigbrain.com/r/created_by", domain=("Task", "Comment"), range=("User",), cardinality="many_to_one", inverse="CREATOR_OF", inverse_iri="https://littlebigbrain.com/r/creator_of")
    MEMBER_OF = StarterRelation(name="MEMBER_OF", iri="https://littlebigbrain.com/r/member_of", domain=("User",), range=("Team",), cardinality="many_to_many", inverse="HAS_MEMBER", inverse_iri="https://littlebigbrain.com/r/has_member")
    IN_STAGE = StarterRelation(name="IN_STAGE", iri="https://littlebigbrain.com/r/in_stage", domain=("Task",), range=("Stage",), cardinality="many_to_one", inverse="STAGE_HOLDS", inverse_iri="https://littlebigbrain.com/r/stage_holds")
    IN_PIPELINE = StarterRelation(name="IN_PIPELINE", iri="https://littlebigbrain.com/r/in_pipeline", domain=("Stage",), range=("Pipeline",), cardinality="many_to_one", inverse="PIPELINE_HOLDS", inverse_iri="https://littlebigbrain.com/r/pipeline_holds")
    TAGGED_WITH = StarterRelation(name="TAGGED_WITH", iri="https://littlebigbrain.com/r/tagged_with", domain=("Task",), range=("Tag",), cardinality="many_to_many", inverse="TAGS", inverse_iri="https://littlebigbrain.com/r/tags")
    BROADER = StarterRelation(name="BROADER", iri="https://littlebigbrain.com/r/broader", domain=("Tag",), range=("Tag",), cardinality="many_to_many", inverse="NARROWER", inverse_iri="https://littlebigbrain.com/r/narrower")
    FOR_ORGANIZATION = StarterRelation(name="FOR_ORGANIZATION", iri="https://littlebigbrain.com/r/for_organization", domain=("Issue",), range=("Organization",), cardinality="many_to_many", inverse="ORGANIZATION_OF", inverse_iri="https://littlebigbrain.com/r/organization_of")
    IN_TEAM = StarterRelation(name="IN_TEAM", iri="https://littlebigbrain.com/r/in_team", domain=("Task", "Project", "Pipeline", "Iteration"), range=("Team",), cardinality="many_to_many", inverse="TEAM_HOLDS", inverse_iri="https://littlebigbrain.com/r/team_holds")
    IN_PROJECT = StarterRelation(name="IN_PROJECT", iri="https://littlebigbrain.com/r/in_project", domain=("Task",), range=("Project",), cardinality="many_to_one", inverse="PROJECT_HOLDS", inverse_iri="https://littlebigbrain.com/r/project_holds")
    IN_MILESTONE = StarterRelation(name="IN_MILESTONE", iri="https://littlebigbrain.com/r/in_milestone", domain=("Task",), range=("Milestone",), cardinality="many_to_one", inverse="MILESTONE_HOLDS", inverse_iri="https://littlebigbrain.com/r/milestone_holds")
    MILESTONE_OF = StarterRelation(name="MILESTONE_OF", iri="https://littlebigbrain.com/r/milestone_of", domain=("Milestone",), range=("Project",), cardinality="many_to_one", inverse="HAS_MILESTONE", inverse_iri="https://littlebigbrain.com/r/has_milestone")
    IN_ITERATION = StarterRelation(name="IN_ITERATION", iri="https://littlebigbrain.com/r/in_iteration", domain=("Task",), range=("Iteration",), cardinality="many_to_one", inverse="ITERATION_HOLDS", inverse_iri="https://littlebigbrain.com/r/iteration_holds")
    LED_BY = StarterRelation(name="LED_BY", iri="https://littlebigbrain.com/r/led_by", domain=("Project",), range=("User",), cardinality="many_to_one", inverse="LEADS", inverse_iri="https://littlebigbrain.com/r/leads")
    SUBTASK_OF = StarterRelation(name="SUBTASK_OF", iri="https://littlebigbrain.com/r/subtask_of", domain=("Task",), range=("Task",), cardinality="many_to_one", inverse="HAS_SUBTASK", inverse_iri="https://littlebigbrain.com/r/has_subtask")
    BLOCKS = StarterRelation(name="BLOCKS", iri="https://littlebigbrain.com/r/blocks", domain=("Task",), range=("Task",), cardinality="many_to_many", inverse="BLOCKED_BY", inverse_iri="https://littlebigbrain.com/r/blocked_by")
    RELATED_TO = StarterRelation(name="RELATED_TO", iri="https://littlebigbrain.com/r/related_to", domain=("Task",), range=("Task",), cardinality="many_to_many", inverse=None, inverse_iri=None)
    DUPLICATE_OF = StarterRelation(name="DUPLICATE_OF", iri="https://littlebigbrain.com/r/duplicate_of", domain=("Task",), range=("Task",), cardinality="many_to_one", inverse="HAS_DUPLICATE", inverse_iri="https://littlebigbrain.com/r/has_duplicate")
    COMMENT_ON = StarterRelation(name="COMMENT_ON", iri="https://littlebigbrain.com/r/comment_on", domain=("Comment",), range=("Task",), cardinality="many_to_one", inverse="HAS_COMMENT", inverse_iri="https://littlebigbrain.com/r/has_comment")


class _Work:
    """The Work management starter 1.0.0."""

    id = "work"
    version = "1.0.0"
    label = "Work management"
    classes = _WorkClasses
    properties = _WorkProperties
    relations = _WorkRelations
    questions: tuple[StarterQuestion, ...] = (
        StarterQuestion(id="work-01", text="Which open issues does a team have, by stage and priority?", sparql="PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX p: <https://littlebigbrain.com/p/>\nPREFIX r: <https://littlebigbrain.com/r/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n\nSELECT ?team ?issue ?stage ?stage_category ?priority WHERE {\n  # Input: a team's name. UNDEF answers for every team.\n  VALUES ?team { UNDEF }\n  ?t a/rdfs:subClassOf* c:team ;\n     rdfs:label ?team .\n  ?i a/rdfs:subClassOf* c:issue ;\n     r:in_team ?t ;\n     rdfs:label ?issue ;\n     r:in_stage ?s .\n  ?s a/rdfs:subClassOf* c:stage ;\n     rdfs:label ?stage ;\n     p:is_closed false .\n  OPTIONAL { ?s p:stage_category ?stage_category }\n  OPTIONAL { ?i p:priority ?priority }\n}\nORDER BY ?team ?stage ?priority ?issue\n"),
        StarterQuestion(id="work-02", text="What is assigned to a user, and what is overdue?", sparql="PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX p: <https://littlebigbrain.com/p/>\nPREFIX r: <https://littlebigbrain.com/r/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n\nSELECT ?user ?task ?due_at ?overdue WHERE {\n  # Input: a user's name. UNDEF answers for every user.\n  VALUES ?user { UNDEF }\n  ?u a/rdfs:subClassOf* c:user ;\n     rdfs:label ?user .\n  ?t a/rdfs:subClassOf* c:task ;\n     r:assigned_to ?u ;\n     rdfs:label ?task .\n  FILTER NOT EXISTS { ?t p:completed_at ?completed_at }\n  FILTER NOT EXISTS { ?t p:canceled_at ?canceled_at }\n  OPTIONAL { ?t p:due_at ?due_at }\n  BIND(BOUND(?due_at) && ?due_at < NOW() AS ?overdue)\n}\nORDER BY ?user ?due_at\n"),
        StarterQuestion(id="work-03", text="Which issues are in the current iteration, and how many are done?", sparql="PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX p: <https://littlebigbrain.com/p/>\nPREFIX r: <https://littlebigbrain.com/r/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n\nSELECT ?iteration ?issue ?stage_category ?issues ?done WHERE {\n  ?it a/rdfs:subClassOf* c:iteration ;\n      rdfs:label ?iteration ;\n      p:start_at ?start_at ;\n      p:end_at ?end_at .\n  # The current iteration: started and not ended.\n  FILTER(?start_at <= NOW() && ?end_at >= NOW())\n  ?i a/rdfs:subClassOf* c:issue ;\n     r:in_iteration ?it ;\n     rdfs:label ?issue .\n  OPTIONAL {\n    ?i r:in_stage ?s .\n    ?s a/rdfs:subClassOf* c:stage ;\n       p:stage_category ?stage_category .\n  }\n  # How many issues the iteration holds, and how many are done.\n  {\n    SELECT ?it (COUNT(?j) AS ?issues)\n           (SUM(IF(COALESCE(?category, \"\") = \"completed\", 1, 0)) AS ?done) WHERE {\n      ?j a/rdfs:subClassOf* c:issue ;\n         r:in_iteration ?it .\n      OPTIONAL { ?j r:in_stage/p:stage_category ?category }\n    }\n    GROUP BY ?it\n  }\n}\nORDER BY ?iteration ?stage_category ?issue\n"),
        StarterQuestion(id="work-04", text="Which tasks block a task, directly or indirectly?", sparql="PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX p: <https://littlebigbrain.com/p/>\nPREFIX r: <https://littlebigbrain.com/r/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n\nSELECT ?task ?blocker ?status WHERE {\n  # Input: the blocked task's name. UNDEF answers for every task.\n  VALUES ?task { UNDEF }\n  ?t a/rdfs:subClassOf* c:task ;\n     rdfs:label ?task .\n  # Directly or indirectly: one or more BLOCKS steps.\n  ?b r:blocks+ ?t ;\n     rdfs:label ?blocker .\n  OPTIONAL { ?b p:status ?status }\n}\nORDER BY ?task ?blocker\n"),
        StarterQuestion(id="work-05", text="What is the progress and health of a project, and who leads it?", sparql="PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX p: <https://littlebigbrain.com/p/>\nPREFIX r: <https://littlebigbrain.com/r/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n\nSELECT ?project ?progress ?health ?target_date ?lead WHERE {\n  # Input: a project's name. UNDEF answers for every project.\n  VALUES ?project { UNDEF }\n  ?pr a/rdfs:subClassOf* c:project ;\n      rdfs:label ?project .\n  OPTIONAL { ?pr p:progress ?progress }\n  OPTIONAL { ?pr p:health ?health }\n  OPTIONAL { ?pr p:target_date ?target_date }\n  OPTIONAL {\n    ?pr r:led_by ?u .\n    ?u a/rdfs:subClassOf* c:user ;\n       rdfs:label ?lead .\n  }\n}\nORDER BY ?project\n"),
        StarterQuestion(id="work-06", text="Which issues belong to a milestone of a project, and when is it due?", sparql="PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX p: <https://littlebigbrain.com/p/>\nPREFIX r: <https://littlebigbrain.com/r/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n\nSELECT ?project ?milestone ?target_date ?issue WHERE {\n  # Input: a project's name. UNDEF answers for every project.\n  VALUES ?project { UNDEF }\n  ?pr a/rdfs:subClassOf* c:project ;\n      rdfs:label ?project .\n  ?m a/rdfs:subClassOf* c:milestone ;\n     r:milestone_of ?pr ;\n     rdfs:label ?milestone .\n  OPTIONAL { ?m p:target_date ?target_date }\n  ?i a/rdfs:subClassOf* c:issue ;\n     r:in_milestone ?m ;\n     rdfs:label ?issue .\n}\nORDER BY ?project ?target_date ?issue\n"),
        StarterQuestion(id="work-07", text="Which sub-tasks does a task have, at any depth?", sparql="PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX p: <https://littlebigbrain.com/p/>\nPREFIX r: <https://littlebigbrain.com/r/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n\nSELECT ?task ?subtask ?status WHERE {\n  # Input: the parent task's name. UNDEF answers for every task.\n  VALUES ?task { UNDEF }\n  ?t a/rdfs:subClassOf* c:task ;\n     rdfs:label ?task .\n  # At any depth: one or more SUBTASK_OF steps.\n  ?s r:subtask_of+ ?t ;\n     rdfs:label ?subtask .\n  OPTIONAL { ?s p:status ?status }\n}\nORDER BY ?task ?subtask\n"),
        StarterQuestion(id="work-08", text="Which issues carry a label, or a narrower label?", sparql="PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX r: <https://littlebigbrain.com/r/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n\nSELECT ?label ?issue ?tagged_with WHERE {\n  # Input: a label's name. UNDEF answers for every label.\n  VALUES ?label { UNDEF }\n  ?t a/rdfs:subClassOf* c:tag ;\n     rdfs:label ?label .\n  ?i a/rdfs:subClassOf* c:issue ;\n     rdfs:label ?issue ;\n     r:tagged_with ?direct .\n  # The label itself or a narrower one: zero or more BROADER steps.\n  ?direct r:broader* ?t ;\n          rdfs:label ?tagged_with .\n}\nORDER BY ?label ?issue\n"),
        StarterQuestion(id="work-09", text="Which issues did a customer organization ask for?", sparql="PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX p: <https://littlebigbrain.com/p/>\nPREFIX r: <https://littlebigbrain.com/r/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n\nSELECT ?organization ?domain ?issue WHERE {\n  # Input: the organization's web domain. UNDEF answers for every\n  # organization.\n  VALUES ?domain { UNDEF }\n  ?o a/rdfs:subClassOf* c:organization ;\n     rdfs:label ?organization ;\n     p:domain ?domain .\n  ?i a/rdfs:subClassOf* c:issue ;\n     r:for_organization ?o ;\n     rdfs:label ?issue .\n}\nORDER BY ?organization ?issue\n"),
        StarterQuestion(id="work-10", text="What did a user create or comment on this week?", sparql="PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX p: <https://littlebigbrain.com/p/>\nPREFIX r: <https://littlebigbrain.com/r/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\nPREFIX xsd: <http://www.w3.org/2001/XMLSchema#>\n\nSELECT ?user ?action ?item ?created_at WHERE {\n  # Inputs: a user's name, and the start of the week as xsd:dateTime. UNDEF\n  # answers for every user or date.\n  VALUES (?user ?since) { (UNDEF UNDEF) }\n  ?u a/rdfs:subClassOf* c:user ;\n     rdfs:label ?user .\n  {\n    ?t a/rdfs:subClassOf* c:task ;\n       r:created_by ?u ;\n       rdfs:label ?item ;\n       p:created_at ?created_at .\n    BIND(\"created\" AS ?action)\n  } UNION {\n    ?k a/rdfs:subClassOf* c:comment ;\n       r:created_by ?u ;\n       r:comment_on ?t ;\n       p:created_at ?created_at .\n    ?t rdfs:label ?item .\n    BIND(\"commented on\" AS ?action)\n  }\n  FILTER(!BOUND(?since) || ?created_at >= ?since)\n}\nORDER BY ?user DESC(?created_at)\n"),
        StarterQuestion(id="work-11", text="How long do issues take from start to completion, per team?", sparql="PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX p: <https://littlebigbrain.com/p/>\nPREFIX r: <https://littlebigbrain.com/r/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n\nSELECT ?team ?issue ?started_at ?completed_at WHERE {\n  # Input: a team's name. UNDEF answers for every team.\n  VALUES ?team { UNDEF }\n  ?t a/rdfs:subClassOf* c:team ;\n     rdfs:label ?team .\n  # The time an issue took is completed_at minus started_at: the data plane\n  # does not subtract date-times yet, so the query returns both.\n  ?i a/rdfs:subClassOf* c:issue ;\n     r:in_team ?t ;\n     rdfs:label ?issue ;\n     p:started_at ?started_at ;\n     p:completed_at ?completed_at .\n}\nORDER BY ?team ?completed_at\n"),
        StarterQuestion(id="work-12", text="Which tasks repeat or relate to a given task?", sparql="PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX r: <https://littlebigbrain.com/r/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n\nSELECT ?task ?link ?other WHERE {\n  # Input: a task's name. UNDEF answers for every task.\n  VALUES ?task { UNDEF }\n  ?t a/rdfs:subClassOf* c:task ;\n     rdfs:label ?task .\n  { ?x r:duplicate_of ?t . BIND(\"duplicate\" AS ?link) }\n  UNION\n  { ?t r:duplicate_of ?x . BIND(\"original\" AS ?link) }\n  UNION\n  # RELATED_TO is symmetric: the graph holds both directions.\n  { ?t r:related_to ?x . BIND(\"related\" AS ?link) }\n  ?x rdfs:label ?other .\n}\nORDER BY ?task ?link ?other\n"),
        StarterQuestion(id="work-13", text="Which open issues have no assignee or no estimate?", sparql="PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX p: <https://littlebigbrain.com/p/>\nPREFIX r: <https://littlebigbrain.com/r/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n\nSELECT ?issue ?no_assignee ?no_estimate WHERE {\n  ?i a/rdfs:subClassOf* c:issue ;\n     rdfs:label ?issue .\n  # Open: not in a closed stage.\n  FILTER NOT EXISTS { ?i r:in_stage/p:is_closed true }\n  BIND(NOT EXISTS { ?i r:assigned_to ?u } AS ?no_assignee)\n  BIND(NOT EXISTS { ?i p:estimate ?e } AS ?no_estimate)\n  FILTER(?no_assignee || ?no_estimate)\n}\nORDER BY ?issue\n"),
        StarterQuestion(id="work-14", text="Who are the members of a team?", sparql="PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX p: <https://littlebigbrain.com/p/>\nPREFIX r: <https://littlebigbrain.com/r/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n\nSELECT ?team ?member ?email WHERE {\n  # Input: a team's name. UNDEF answers for every team.\n  VALUES ?team { UNDEF }\n  ?t a/rdfs:subClassOf* c:team ;\n     rdfs:label ?team .\n  ?u a/rdfs:subClassOf* c:user ;\n     r:member_of ?t ;\n     rdfs:label ?member .\n  OPTIONAL { ?u p:email ?email }\n}\nORDER BY ?team ?member\n"),
        StarterQuestion(id="work-15", text="What are a team's workflow stages, in order?", sparql="PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX p: <https://littlebigbrain.com/p/>\nPREFIX r: <https://littlebigbrain.com/r/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n\nSELECT ?team ?pipeline ?display_order ?stage ?stage_category WHERE {\n  # Input: a team's name. UNDEF answers for every team.\n  VALUES ?team { UNDEF }\n  ?t a/rdfs:subClassOf* c:team ;\n     rdfs:label ?team .\n  ?pl a/rdfs:subClassOf* c:pipeline ;\n      r:in_team ?t ;\n      rdfs:label ?pipeline .\n  ?s a/rdfs:subClassOf* c:stage ;\n     r:in_pipeline ?pl ;\n     rdfs:label ?stage .\n  OPTIONAL { ?s p:display_order ?display_order }\n  OPTIONAL { ?s p:stage_category ?stage_category }\n}\nORDER BY ?team ?pipeline ?display_order\n"),
        StarterQuestion(id="work-16", text="Where does an issue come from: which system, which id, which link?", sparql="PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX p: <https://littlebigbrain.com/p/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n\nSELECT ?issue ?identifier ?source_system ?source_id ?source_url WHERE {\n  # Input: the issue's identifier, such as ENG-123. UNDEF answers for every\n  # issue.\n  VALUES ?identifier { UNDEF }\n  ?i a/rdfs:subClassOf* c:issue ;\n     rdfs:label ?issue ;\n     p:identifier ?identifier .\n  OPTIONAL { ?i p:source_system ?source_system }\n  OPTIONAL { ?i p:source_id ?source_id }\n  OPTIONAL { ?i p:source_url ?source_url }\n}\nORDER BY ?identifier\n"),
        StarterQuestion(id="work-17", text="Which issues were canceled, and of what type?", sparql="PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX p: <https://littlebigbrain.com/p/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n\nSELECT ?issue ?issue_type ?canceled_at WHERE {\n  ?i a/rdfs:subClassOf* c:issue ;\n     rdfs:label ?issue ;\n     p:canceled_at ?canceled_at .\n  OPTIONAL { ?i p:issue_type ?issue_type }\n}\nORDER BY DESC(?canceled_at)\n"),
        StarterQuestion(id="work-18", text="Which open tasks remain in a project, and who does them?", sparql="PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX p: <https://littlebigbrain.com/p/>\nPREFIX r: <https://littlebigbrain.com/r/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n\nSELECT ?project ?task ?due_at ?assignee WHERE {\n  # Input: a project's name. UNDEF answers for every project.\n  VALUES ?project { UNDEF }\n  ?pr a/rdfs:subClassOf* c:project ;\n      rdfs:label ?project .\n  ?t a/rdfs:subClassOf* c:task ;\n     r:in_project ?pr ;\n     rdfs:label ?task .\n  FILTER NOT EXISTS { ?t p:completed_at ?completed_at }\n  FILTER NOT EXISTS { ?t p:canceled_at ?canceled_at }\n  FILTER NOT EXISTS { ?t r:in_stage/p:is_closed true }\n  OPTIONAL { ?t p:due_at ?due_at }\n  OPTIONAL {\n    ?t r:assigned_to ?u .\n    ?u a/rdfs:subClassOf* c:user ;\n       rdfs:label ?assignee .\n  }\n}\nORDER BY ?project ?due_at ?task\n"),
    )


work = _Work()


__all__ = ["StarterClass", "StarterProperty", "StarterRelation", "StarterQuestion", "crm", "documents", "work"]
